import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
// import Head from "next/head";
import { Inknut_Antiqua } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const inknut = Inknut_Antiqua({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inknut.className} antialiased bg-[#eeeeee81]`}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#EEEEEE]`}
      >
        <Navbar />
        <div className="max-w-5xl mx-auto">{children}</div>
      </body>
    </html>
  );
}
